export const GET_ALL_SURVEYS_LOADING = "GET_ALL_SURVEYS_LOADING";
export const GET_ALL_SURVEYS_SUCCESS = "GET_ALL_SURVEYS_SUCCESS";
export const GET_ALL_SURVEYS_FAILURE = "GET_ALL_SURVEYS_FAILURE";

export const CREATE_SURVEY_LOADING = "CREATE_SURVEY_LOADING";
export const CREATE_SURVEY_SUCCESS = "CREATE_SURVEY_SUCCESS";
export const CREATE_SURVEY_FAILURE = "CREATE_SURVEY_FAILURE";
export const CREATE_SURVEY_RESET = "CREATE_SURVEY_RESET";
